language: c
sudo: required
dist: bionic
install:
  - sudo apt-get install -y python-pytest python-numpy python-pygame python-pytest-cov python-coverage
script:
  - PYTHONPATH=. py.test --cov
  - PYTHONPATH=. python-coverage xml
git:
  submodules: false
after_success:
    - bash <(curl -s https://codecov.io/bash)
